apiVersion: v1
kind: Pod
metadata:
  name: pv-pod-with-claim-default-storageclass
spec:
  volumes:
    - name: pv-storage
      persistentVolumeClaim:
        claimName: pv-claim-default-storageclass
  shareProcessNamespace: true
  containers:
    - name: pv-container
      image: busybox
      command:
        - "sleep"
        - "infinity"
      resources: {}
      volumeMounts:
        - mountPath: "/mnt"
          name: pv-storage
---
apiVersion: v1
kind: Pod
metadata:
  name: pv-pod-with-claim-local
spec:
  volumes:
    - name: pv-storage
      persistentVolumeClaim:
        claimName: pv-claim-manual-local
  shareProcessNamespace: true
  containers:
    - name: pv-container
      image: busybox
      command:
        - "sleep"
        - "infinity"
      resources: {}
      volumeMounts:
        - mountPath: "/mnt"
          name: pv-storage
---
apiVersion: v1
kind: Pod
metadata:
  name: pv-pod-with-claim-hostpath
spec:
  volumes:
    - name: pv-storage
      persistentVolumeClaim:
        claimName: pv-claim-manual-hostpath
  shareProcessNamespace: true
  containers:
    - name: pv-container
      image: busybox
      command:
        - "sleep"
        - "infinity"
      resources: {}
      volumeMounts:
        - mountPath: "/mnt"
          name: pv-storage

---
apiVersion: v1
kind: Pod
metadata:
  name: pv-pod-hostpath
spec:
  volumes:
    - name: pv-storage
      hostPath:
        path: "/mnt/data"
  shareProcessNamespace: true
  containers:
    - name: pv-container
      image: busybox
      command:
        - "sleep"
        - "infinity"
      resources: {}
      volumeMounts:
        - mountPath: "/mnt"
          name: pv-storage
