apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim-default-storageclass
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim-manual-hostpath
spec:
  storageClassName: manual-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim-manual-local
spec:
  storageClassName: manual-local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim-unbound
spec:
  storageClassName: unbound
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
