apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: kopy
spec:
  version: "{{ .TagName }}"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/websi96/kubectl-kopy/releases/download/{{ .TagName }}/kubectl-kopy_linux_amd64.tar.gz" .TagName }}
    files:
    - from: "./kopy"
      to: "."
    - from: LICENSE
      to: "."
    bin: "kopy"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    {{addURIAndSha "https://github.com/websi96/kubectl-kopy/releases/download/{{ .TagName }}/kubectl-kopy_darwin_amd64.tar.gz" .TagName }}
    files:
    - from: "./kopy"
      to: "."
    - from: LICENSE
      to: "."
    bin: "kopy"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    {{addURIAndSha "https://github.com/websi96/kubectl-kopy/releases/download/{{ .TagName }}/kubectl-kopy_windows_amd64.zip" .TagName }}
    files:
    - from: "/kopy.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "kopy.exe"
  shortDescription: Copy Contents from PVs
  homepage: https://github.com/websi96/kubectl-kopy
  description: |
    Kubectl plugins to download content from a PV.
